### ISSUE TITLE
maven 3.6.2 install 时提示错误Unable to execute gpg command

### ISSUE THREAD

**Issue by wangpeng2020** [liuhuagui/smalldoc#10]
我是用的时maven 3.6.2
执行maven install时会提示以下错误：
Failed to execute goal org.apache.maven.plugins:maven-gpg-plugin:1.6:sign (sign-artifacts) on project smalldoc: Unable to execute gpg command

试了一下可以加入pluginManagement解决，但我没有测试其他maven版本
<build>
   <pluginManagement>
   <plugins>
      <plugin></plugin>
      ...
       <plugin></plugin>
    </plugins>
</pluginManagement>
</build>

**Comment by liuhuagui** [comment]
gpg是用来发布时加密的，临时打包使用，建议你注释掉这些用来发布的plugin

**Comment by wangpeng2020** [comment]
好的，明白了，刚接触还不太熟悉这东西。

**Comment by liuhuagui** [comment]
如果可以，建议将“类名判断”升级成可配置的方式
