### ISSUE TITLE
继承之后报错

### ISSUE THREAD

**Issue by silentself** [liuhuagui/smalldoc#13]
Factory method 'smallDocServletRegistrationBean' threw exception; nested exception is java.lang.NullPointerException

**Comment by liuhuagui** [comment]
继承？希望给出完整错误栈

**Comment by silentself** [comment]
这个错误又没了，我之前用的是2.3，换成2.5版本之后，可以正常使用了，但是有一个新问题，由于我的是maven聚合项目，参数smalldoc.source-paths以相对路径设置好像没有生效

**Comment by silentself** [comment]
目前我只能以绝对路径设置

**Comment by silentself** [comment]
已经解决了，3q
