### ISSUE TITLE
设置scope为test无法生效

### ISSUE THREAD

**Issue by silentself** [liuhuagui/smalldoc#15]
见文档中强烈推荐，将maven坐标scope设置为test，我按着这种方式设置完之后，访问网址，404，请问是什么原因

**Comment by silentself** [comment]
您好，还有一个很致命的问题，如果是复杂传参和返回对象多层自定义的好像就解析不出来了

**Comment by silentself** [comment]
`public class AuthListSearchFEO {

    /**
     * 用户id
     */
    @NotNull(message = "用户id")
    private Long uuid;

    /**
     * list
     */
    private List<String> list;

    /**
     * 这是个自定义的对象
     */
    private AuthListVO authListVO;
}`
比如我传递的参数是一个自定义的类型AuthListSearchFEO，里面又包了一个自定义的对象，还有里面又集合和数组的，使用类似@{uuid*,list}这种方式是不能用的

**Comment by silentself** [comment]
返回对象如果多层自定义好像没事，只有当子节点定义的对象和父节点定义的对象是一类对象的时候会解析不出来

**Comment by liuhuagui** [comment]
1. &lt;scope>设置为test是在发布到生产环境时使用，避免该jar包被repackage到可执行的jar包中
2. 你需要@{uuid*,authListVO.xxx}，比如下面这样，各种复杂情况都罗列出来了
```java
 /**
     * 测试接口
     * @param oaCopy  @{authorId*,testlist.authorId*,originalArticleCopy.authorId*,paragraph.content}
     * @return data-草稿ID
     */
    @RequestMapping("action")
    public Result<Long> test(OriginalArticleCopy oaCopy, HttpServletRequest request) {
        return null;
    }
```
```java
public class OriginalArticleCopy extends Base<OriginalArticleCopy> implements Serializable {
    /**
     * list
     */
    private List<OriginalArticleCopy> testlist;

    private OriginalArticleCopy originalArticleCopy;

    public OriginalArticleCopy getOriginalArticleCopy() {
        return originalArticleCopy;
    }

    public void setOriginalArticleCopy(OriginalArticleCopy originalArticleCopy) {
        this.originalArticleCopy = originalArticleCopy;
    }

    public List<OriginalArticleCopy> getTestlist() {
        return testlist;
    }

    public void setTestlist(List<OriginalArticleCopy> testlist) {
        this.testlist = testlist;
    }

    private Paragraph paragraph;

    /**
     * 作者Id
     */
    private String authorId;
}
```

**Comment by liuhuagui** [comment]
![image](https://user-images.githubusercontent.com/21290865/71142846-92dfec80-2253-11ea-902d-2f6cc6a604e7.png)

**Comment by silentself** [comment]
这种方式有个问题，

`
@Data
public class AuthListSearchFEO {

    /**
     * 用户id
     */
    @NotNull(message = "用户id")
    private Long uuid;

    /**
     * 权限
     */
    private List<AuthListVO> authListVOList;

    /**
     * 权限
     */
    private AuthListVO authListVO;

    /**
     * list
     */
    private List<String> list;
}
`
当用上面的对象来接收请求参数的时候
①、authListVOList和authListVO从界面上是看不出来要传递的参数是数组还是只接收一个
②、List<String> 或者String[] 这种类型的参数应该怎么表述

**Comment by liuhuagui** [comment]
多谢了，这是Bug，应该和下面这个情况一致才对，我会去更改它
```java
/**
     * 测试接口
     * @param oaCopy  @{authorId*,testlist.authorId*}
     * @return data-草稿ID
     */
    @RequestMapping("action")
    public Result<Long> test(List<OriginalArticleCopy> oaCopy, HttpServletRequest request) {
        return null;
    }
```
![image](https://user-images.githubusercontent.com/21290865/71149222-e14bb600-2268-11ea-8cd3-15aceccc787d.png)

**Comment by silentself** [comment]
String[] 和“List\<String\>”这种类型的参数的目前可以表述吗，毕竟Java原生类型的数据或集合形式的传参还是挺多的，自定义类型的数据和集合可以拿别的方式替代 但是这个是不行的

**Comment by liuhuagui** [comment]
可以，但是目前只支持作为参数类型，而不是作为实体类型中的字段（这是个Bug正在修改）。
```java
  /**
     * 测试接口
     * @param a  数组类型@*
     * @param b  集合类型
     * @param oaCopy  @{authorId*,array0,array1,array2,testlist[].authorId*}
     * @param oaCopies  @{authorId*,array0,array1,array2,testlist[].authorId*}
     * @return data-草稿ID
     */
    @RequestMapping("action")
    public Result<Long> test(String[] a, List<String> b, List<OriginalArticleCopy> oaCopies, OriginalArticleCopy oaCopy, HttpServletRequest request) {
        return null;
    }
```

**Comment by silentself** [comment]
期待能快点改好啊  我们项目组新项目技术栈调研时间马上就要结束了  技术选型文档一旦确定就不好更改了

**Comment by liuhuagui** [comment]
好的，改完告诉你

**Comment by liuhuagui** [comment]
感受下，这样OK吗?
```java
/**
     * 测试接口
     * @param a  数组类型@*
     * @param b  集合类型
     * @param oaCopy  @{authorId*,array0,array1,array2,testlist.authorId*}
     * @param oaCopies  @{authorId*,array0,array1,array2,testlist.authorId*}
     * @return data-草稿ID
     */
    @RequestMapping("action")
    public Result<Long> test(String[] a, List<String> b, List<OriginalArticleCopy> oaCopies, OriginalArticleCopy oaCopy, HttpServletRequest request) {
        return null;
    }
```
```java
public class OriginalArticleCopy extends Base<OriginalArticleCopy> implements Serializable {
    /**
     * 集合0
     */
    private List<String> array0;
    /**
     * 集合1
     */
    private List<Long> array1;
    /**
     * 集合2
     */
    private String[] array2;
    /**
     * list
     */
    private List<OriginalArticleCopy> testlist;
    /**
     * 作者Id
     */
    private String authorId;
}
```
![image](https://user-images.githubusercontent.com/21290865/71239559-cdc04e00-2341-11ea-8315-855588e0e115.png)
![image](https://user-images.githubusercontent.com/21290865/71239571-d9ac1000-2341-11ea-9dea-6b1e033c6032.png)

**Comment by liuhuagui** [comment]
如果可以，加我微信，skk201186，我把jar包发给你，因为这次版本改动可能会很大，还有一些功能没能立刻加上不能直接发布到Maven仓库上，你急着用，先把这个版本给你

**Comment by silentself** [comment]
我觉的这块其实你那边没必要显示这么仔细，不论是集合形式的还是数组形式的，其实传参方式在json种都是一样的，毕竟json传参还是最流行的类型，因此不论是集合还是数组，类型那块都显示数组就ok，个人建议啊

**Comment by silentself** [comment]
或者你可以参考一下swagger-ui的显示方式，swagger最致命的弱点就是代码侵入，作者这个完全避免了。但是swagger-ui的文档风格还是非常不错的

**Comment by liuhuagui** [comment]
之前想过，但是简单传参可以，但是复杂传参如果不显示会产生混淆

**Comment by liuhuagui** [comment]
贵公司是？

**Comment by silentself** [comment]
谷武科技，融媒体行业的

**Comment by silentself** [comment]
我加你微信了
