### ISSUE TITLE
使用properties文件的时候要注意集合的赋值

### ISSUE THREAD

**Issue by hfq-chenghongwei** [liuhuagui/smalldoc#2]
spring.profiles=dev
smalldoc.source-paths[0]=D:\\hhz\\hhz-platform\\src\\main\\java
smalldoc.packages[0]=com.cheng.hhz.controller.hello
smalldoc.project-name=mydoc
smalldoc.enabled=true
smalldoc.url-pattern=/smalldoc/*

**Comment by liuhuagui** [comment]
这个是无法生效？还是？

**Comment by hfq-chenghongwei** [comment]
![image](https://user-images.githubusercontent.com/35718434/67097993-df746080-f1ed-11e9-8a46-3bd71222967e.png)
**为什么会加载两遍，当我不写smalldoc.source-paths[0]，程序无法启动**

**Comment by liuhuagui** [comment]
我明白了，这是一个bug，因为程序已经默认解析了您的源码路径，但是忘记解决null问题，你可以使用空白字符串尝试一下！会尽快更新修复该问题，多谢您的支持！

**Comment by liuhuagui** [comment]
[2.3.1更新日志](https://github.com/liuhuagui/smalldoc/blob/master/doc/smalldoc-2.3.1.md)
