### ISSUE TITLE
注释用法

### ISSUE THREAD

**Issue by brues** [liuhuagui/smalldoc#3]
![image](https://user-images.githubusercontent.com/7028735/67172661-c5ee3700-f3ee-11e9-9600-3049c9dcb639.png)

我使用自己习惯的几个文档注释感觉生成的api文档并不是很友好，能给一个使用注释生成文档的例子大全吗？或者您私人微信能加一下吗？我有几个用法的问题想问您

**Comment by liuhuagui** [comment]
支持html格式的注释，以及@param、@author、@return标签，有额外需求可以直接提出，多谢支持

**Comment by liuhuagui** [comment]
[2.3.1更新日志](https://github.com/liuhuagui/smalldoc/blob/master/doc/smalldoc-2.3.1.md)
