### ISSUE TITLE
多体项目报错

### ISSUE THREAD

**Issue by jiangxiao0215** [liuhuagui/smalldoc#5]
![未命名1571620277](https://user-images.githubusercontent.com/20721712/67177026-343af580-f3ff-11e9-9ba7-6a4285481a76.png)
![未命名1571620136](https://user-images.githubusercontent.com/20721712/67177029-3735e600-f3ff-11e9-9452-e90a2214c58f.png)
![未命名1571620079](https://user-images.githubusercontent.com/20721712/67177033-3bfa9a00-f3ff-11e9-8ab9-09aa8262bae6.png)
![未命名1571620063](https://user-images.githubusercontent.com/20721712/67177035-4026b780-f3ff-11e9-860a-337753ae91ae.png)
配置截图如上

**Comment by liuhuagui** [comment]
您好，该错误不是由于多模块，应该是您使用了自定义的Mapping注解，可以给出注解用法和代码吗，我做下兼容

**Comment by liuhuagui** [comment]
@jiangxiao0215

**Comment by jiangxiao0215** [comment]
> 您好，该错误不是由于多模块，应该是您使用了自定义的Mapping注解，可以给出注解用法和代码吗，我做下兼容

![未命名1571638879](https://user-images.githubusercontent.com/20721712/67181072-1a54df00-f40e-11e9-802d-217158172028.png)
没有自定义注解 ，在新的空的项目里引用这个source-paths就不会报错

**Comment by liuhuagui** [comment]
尝试将Mapping属性写成数组的形式

**Comment by liuhuagui** [comment]
[2.3.1更新日志](https://github.com/liuhuagui/smalldoc/blob/master/doc/smalldoc-2.3.1.md)
