### ISSUE TITLE
请求和返回参数集合对象属性未生成

### ISSUE THREAD

**Issue by jiangxiao0215** [liuhuagui/smalldoc#6]
![未命名1571635545](https://user-images.githubusercontent.com/20721712/67178763-86334980-f406-11e9-885c-55c2a422ba44.png)
![未命名1571635705](https://user-images.githubusercontent.com/20721712/67178805-af53da00-f406-11e9-9dc7-16e3c9797e20.png)

**Comment by liuhuagui** [comment]
抱歉，我会完善文档的。HoQueryMatReqListCo的完全限定名是？是否属于其他Jar或者module？

**Comment by jiangxiao0215** [comment]
> 抱歉，我会完善文档的。HoQueryMatReqListCo的完全限定名是？是否属于其他Jar或者module？
不在
Controller ：wms-output\src\main\java\com\inossem\wms\controller\output\HoMatReqOutputController.java
参数集 : wms-model\src\main\java\com\inossem\wms\co\biz\output\HoQueryMatReqListCo.java

**Comment by liuhuagui** [comment]
将该路径添加到source-paths

**Comment by liuhuagui** [comment]
[2.3.1更新日志](https://github.com/liuhuagui/smalldoc/blob/master/doc/smalldoc-2.3.1.md)
